export default {
  email: 'E-mail',
  password: 'Password',
  passwordRetype: 'Retype password',
  subscription: 'Subscription',
  subscriptions: 'Subscriptions',
  myFiles: 'Files',
  login: 'Login',
  entrance: 'Login',
  register: 'Register',
  today: 'Today',
  popup: 'Pop-up',
  code: 'Code',
  info: 'Information',
  pageNames: {
    main: 'Main',
    login: 'Login',
    convertDocument: 'Convert document',
    mergeDocuments: 'Merge documents',
    splitDocument: 'Split document',
    myFiles: 'My files',
    profile: 'Profile',
    subscriptions: 'Subscriptions',
    termsAndConditions: 'Terms and conditions',
  },
  auth: {
    forgotPasswordQuestion: 'Forgot your password?',
    subscriptionNotExistsQuestion: 'Didn\'t subscribed yet?',
    takeFree: 'Get for free',
    incorrectCodeMessage: 'Something goes wrong, please try again',
    typeCodeMessage: 'Insert the code we sent to your e-mail address',
    checkEnterDataMessage: 'Please check the data',
    oldPassword: 'Old password',
    newPassword: 'New password',
    approvePasswordMessage: 'Confirm password',
    setEmailForSentMessage: 'Please add e-mail address to send you verification code',
  },
  messages: {
    somethingWrongTitle: 'Something goes wrong.',
    somethingWrongText: 'Contact the administrator.',
    unauthorizedTitle: 'Session lifetime is over',
    unauthorizedText: 'Please login again',
  },
  documents: {
    maxSize: 'Max size is 50 Mb',
    pages: 'No pages | {n} page | {n} pages',
  },
  actions: {
    goBack: 'Go back',
    send: 'Send',
    close: 'Close',
    addFile: 'Add file',
    restorePassword: 'Forgotten password?',
    setNewPassword: 'Change new password',
    enter: 'Login',
    out: 'Logout',
    change: 'Change',
    approve: 'Confirm',
    approveEmail: 'Confirm e-mail',
    changeEmail: 'Change e-mail address',
    changePassword: 'Change password',
    convertToPdf: 'Convert to PDF',
    convert: 'Convert',
    splitFile: 'Split the file',
    split: 'Split',
    mergePages: 'Merge pages',
    merge: 'Merge',
    dontConvert: 'Не конвертировать',
    select: 'Select',
    scaleDown: 'Scale down',
    scaleUp: 'Scale up',
    scaleSet: 'Scale set up',
  },
  profile: {
    title: 'Profile',
    statistic: {
      load: 'Your files',
      convert: 'Converted files',
      merge: 'Merged files',
      split: 'Splitted files',
    },
    subscribe: {
      resume: 'Renew subscription',
      order: 'Subscribe',
      continueOrder: 'Continue order',
      ends: 'Your subscription expires soon:',
      notExists: 'You haven\'t subscribed yet',
      successPayment: {
        title: 'Success payment',
        message: 'Thank you!',
      },
      errorPayment: {
        title: 'Error during payment!',
        message: 'Please, go to admin - admin@pdf-maker.com',
      },
    },
  },
  footer: {
    rights: 'Pdf Editor {year} © All right received',
    socialLinks: 'Social networks',
    mobileApps: 'Mobile apps',
  },
  modes: {
    convert: {
      title: 'Convert the file',
      subTitle: 'form .DOC, .DOCX, .JPG or .EXCEL to .PDF',
      caption: 'Select the file for converting',
    },
    merge: {
      title: 'Merge files',
      subTitle: 'from several .PDF to one',
      caption: 'Select the file for merge',
    },
    split: {
      title: 'Split the file',
      subTitle: 'from several .PDF to two or more',
      caption: 'Select the file for split',
    },
  },
  subscriptionsData: {
    step: 'Step',
    steps: {
      first: 'Subscription duration',
      second: 'Register account',
    },
    one: {
      title: 'one month',
      features: [
        'Unite account for all your devices',
        'File storage',
        'Download as much as you need',
      ],
      price: '8,99$/month',
      priceCaption: '',
      priceDiscount: '',
    },
    three: {
      title: 'three months', // 3 months premium subscription
      features: [
        'Unite account for all your devices',
        'File storage',
        'Download as much as you need',
      ],
      price: '6,99$/month',
      priceCaption: '13,47$ for 3 month',
      priceDiscount: '-23%',
    },
    year: {
      title: 'for one year', // 1 year premium subscription
      features: [
        'Unite account for all your devices',
        'File storage',
        'Download as much as you need',
      ],
      price: '4,99$/month',
      priceCaption: '47,88$ for one year',
      priceDiscount: '-45%',
    },
  },
};
