export default {
  email: 'Электронная почта',
  password: 'Пароль',
  subscriptions: 'Подписки',
  myFiles: 'Мои файлы',
  login: 'Логин',
  entrance: 'Вход',
  today: 'Сегодня',
  auth: {
    forgotPasswordQuestion: 'Забыли пароль?',
    subscriptionNotExistsQuestion: 'Нет подписки?',
    takeFree: 'Получите бесплатно',
  },
  documents: {
    maxSize: 'Макс. 50 Mb',
  },
  actions: {
    addFile: 'Добавить файл',
    restorePassword: 'Восстановить пароль',
    setNewPassword: 'Задать новый пароль',
    enter: 'Войти',
    change: 'Изменить',
    approve: 'Подтвердить',
    approveEmail: 'Подтвердить почту',
    changeEmail: 'Изменить почту',
    changePassword: 'Сменить пароль',
    convertToPdf: 'Конвертировать в PDF',
    convert: 'Конвертировать',
    splitFile: 'Разделить файл',
    split: 'Разделить',
    dontConvert: 'Не конвертировать',
    select: 'Выбрать',
    scaleDown: 'Уменьшить масштаб',
    scaleUp: 'Увеличить масштаб',
    scaleSet: 'Настроить масштаб',
  },
  profile: {
    title: 'Профиль',
    statistic: {
      load: 'Залито файлов',
      convert: 'Сконвертированно файлов',
      merge: 'Объединено файлов',
      split: 'Разделено файлов',
    },
    subscribe: {
      resume: 'Продлить подписку',
      order: 'Оформить подписку',
      ends: 'Срок подписки истекает:',
      notExists: 'Подписка не оформлена',
    },
  },
};
