export default {
  email: 'Электронная почта',
  password: 'Пароль',
  subscription: 'Подписки',
  subscriptions: 'Подписки',
  myFiles: 'Мои файлы',
  login: 'Логин',
  entrance: 'Вход',
  today: 'Сегодня',
  popup: 'Попап',
  code: 'Код',
  info: 'Информация',

  auth: {
    forgotPasswordQuestion: 'Забыли пароль?',
    subscriptionNotExistsQuestion: 'Нет подписки?',
    takeFree: 'Получите бесплатно',
    incorrectCodeMessage: 'Код не верен, проверьте правильность введенных данных',
    typeCodeMessage: 'Введите код подтверждения, который пришел Вам на почту',
    checkEnterDataMessage: 'Проверьте правильность введенных данных',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    approvePasswordMessage: 'Подтвердите пароль',
    setEmailForSentMessage: 'Введите Вашу почту чтобы, мы смогли вам отправить проверочный код',
  },
  documents: {
    maxSize: 'Макс. 50 Mb',
  },
  actions: {
    send: 'Отправить',
    close: 'Закрыть',
    addFile: 'Добавить файл',
    restorePassword: 'Восстановить пароль',
    setNewPassword: 'Задать новый пароль',
    enter: 'Войти',
    out: 'Выйти',
    change: 'Изменить',
    approve: 'Подтвердить',
    approveEmail: 'Подтвердить почту',
    changeEmail: 'Изменить почту',
    changePassword: 'Сменить пароль',
    convertToPdf: 'Конвертировать в PDF',
    convert: 'Конвертировать',
    splitFile: 'Разделить файл',
    split: 'Разделить',
    dontConvert: 'Не конвертировать',
    select: 'Выбрать',
    scaleDown: 'Уменьшить масштаб',
    scaleUp: 'Увеличить масштаб',
    scaleSet: 'Настроить масштаб',
  },
  profile: {
    title: 'Профиль',
    statistic: {
      load: 'Залито файлов',
      convert: 'Сконвертированно файлов',
      merge: 'Объединено файлов',
      split: 'Разделено файлов',
    },
    subscribe: {
      resume: 'Продлить подписку',
      order: 'Оформить подписку',
      ends: 'Срок подписки истекает:',
      notExists: 'Подписка не оформлена',
    },
  },
  footer: {
    rights: 'Pdf Editor {year} © Все права защищены',
    socialLinks: 'Социальные сети',
    mobileApps: 'Мобильные приложения',
  },
};
